"""Author the local-only bilingual dictionaries from a single matching key set."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
COPY = {'mp.choose': ('Share a keyboard', '共用键盘'),
 'mp.choose_body': ('Two players, two cabinets, one three-minute score duel.', '两位玩家，两个游戏柜，三分钟的得分对战。'),
 'mp.local_splitscreen': ('Local Splitscreen', '本地分屏'),
 'mp.player_one': ('PLAYER 1', '玩家 1'),
 'mp.player_two': ('PLAYER 2', '玩家 2'),
 'mp.local_controls_one': ('A / D  Move · Space  Drop', 'A / D  移动 · 空格  投放'),
 'mp.local_controls_two': ('J / L  Move · K  Drop', 'J / L  移动 · K  投放'),
 'mp.local_ready_one': ('Left · Player 1: A / D to move, Space to drop', '左侧 · 玩家 1：A / D 移动，空格投放'),
 'mp.local_ready_two': ('Right · Player 2: J / L to move, K to drop', '右侧 · 玩家 2：J / L 移动，K 投放'),
 'mp.player_one_win': ('Player 1 wins!', '玩家 1 获胜！'),
 'mp.player_two_win': ('Player 2 wins!', '玩家 2 获胜！'),
 'mp.local_leave_body': ('This ends the match for both players.', '这将结束双方的对战。'),
 'mp.local_live_audio': ('No pausing in multiplayer. The match and timer continue while menus are open.', '多人对战无法暂停。打开菜单时，对战和计时仍会继续。'),
 'mp.local_landscape_body': ('Widen your computer window to see both cabinets. The match keeps running.', '请加宽电脑窗口，显示双方游戏柜。对战会继续进行。'),
 'mp.escape_back': ('Esc to return to title', '按 Esc 返回主菜单'),
 'ui.multiplayer': ('Local multiplayer', '本地双人对战'),
 'mp.heading': ('Mushies · Two-player duel', 'Mushies · 双人对战'),
 'mp.board_finished': ('Finished', '已结束'),
 'mp.board_waiting': ('Waiting for final scores', '等待最终得分'),
 'mp.audio': ('Audio', '声音'),
 'mp.leave': ('Leave match', '离开对战'),
 'mp.next': ('NEXT', '下一个'),
 'mp.controls': ('A/D or ←/→ to aim · Space or click your cabinet to drop', 'A/D 或 ←/→ 瞄准 · 空格或点击你的柜内投放'),
 'mp.leave_title': ('Leave the duel?', '离开对战？'),
 'mp.stay': ('Keep playing', '继续游玩'),
 'mp.back_match': ('Back', '返回'),
 'mp.get_ready': ('Get ready!', '准备开始！'),
 'mp.draw': ('A perfect tie!', '不分上下！'),
 'mp.reason_timeout': ('Time is up. The final scores decide the winner.', '时间到，最终得分决定胜负。'),
 'mp.reason_overflow': ('Both players reached the defeat line. Final scores decide the winner.', '双方都已超线，最终得分决定胜负。'),
 'mp.rematch': ('Play again', '再来一局'),
 'mp.landscape_title': ('Make room for two', '横屏才能同场对战'),
 'loader.loading': ('Preparing your plushies…', '正在准备玩偶…'),
 'loader.downloading': ('Downloading your plushies…', '正在下载玩偶…'),
 'loader.preparing': ('Preparing the playroom…', '正在布置游戏房…'),
 'loader.preparing_detail': ('Almost ready to play.', '马上就能开始游戏。'),
 'loader.progress_unknown': ('Download progress is unavailable.', '暂时无法获取下载进度。'),
 'loader.progress_detail': ('{percent}% · {current} of {total}', '{percent}% · 已下载 {current} / {total}'),
 'loader.progress_label': ('Game download progress', '游戏下载进度'),
 'loader.error': ('The game could not start.', '游戏无法启动。'),
 'loader.error_detail': ('Check your connection, then try again.', '请检查网络连接后重试。'),
 'loader.retry': ('Try again', '重试'),
 'loader.no_canvas': ('Your browser does not support this game.', '当前浏览器不支持此游戏。'),
 'loader.no_js': ('Enable JavaScript to play.', '请启用 JavaScript 后开始游戏。'),
 'app.title': ('Mushies', 'Mushies'),
 'app.tagline': ('Little drops. Big hugs.', '轻轻一放，满满拥抱。'),
 'app.subtitle': ('Keep merging. Keep your pile.', '继续合成，收集更多温暖。'),
 'ui.collection': ('Collection', '玩偶图鉴'),
 'ui.drop_short': ('Drop', '投放'),
 'ui.start': ('Start collecting', '开始收集'),
 'ui.resume': ('Resume', '继续游戏'),
 'ui.restart': ('Restart stage', '重新挑战'),
 'ui.title': ('Return to title', '返回主菜单'),
 'ui.pause': ('Pause', '暂停'),
 'ui.settings': ('Settings', '设置'),
 'ui.leaderboard': ('Leaderboard', '排行榜'),
 'ui.help': ('How to play', '玩法说明'),
 'ui.close': ('Back', '返回'),
 'ui.cancel': ('Keep playing', '继续当前游戏'),
 'ui.confirm': ('Confirm', '确认'),
 'ui.next': ('Next challenge', '下一个挑战'),
 'ui.language': ('Language', '语言'),
 'ui.english': ('English', 'English'),
 'ui.chinese': ('简体中文', '简体中文'),
 'ui.arrow_left': ('←', '←'),
 'ui.arrow_right': ('→', '→'),
 'ui.drop': ('Drop plushie', '放下玩偶'),
 'ui.left': ('Aim left', '向左瞄准'),
 'ui.right': ('Aim right', '向右瞄准'),
 'ui.name': ('Display name', '显示名称'),
 'ui.name_placeholder': ('Name (optional)', '你的昵称（可选）'),
 'ui.player': ('Player', '玩家'),
 'ui.muted': ('Mute all audio', '关闭所有声音'),
 'ui.music_enabled': ('Background music', '背景音乐'),
 'ui.sfx_enabled': ('Sound effects', '音效'),
 'ui.reduced_motion': ('Reduce motion', '减少动态效果'),
 'ui.master': ('Master volume', '总音量'),
 'ui.music': ('Music volume', '音乐音量'),
 'ui.sfx': ('Game effects volume', '游戏音效音量'),
 'ui.ui': ('Interface volume', '界面音效音量'),
 'ui.percent': ('{value}%', '{value}%'),
 'ui.filter': ('Warm screen filter', '暖色画面滤镜'),
 'ui.audio_cue': ('Sound {index} / {count}', '音效 {index} / {count}'),
 'ui.pause_title': ('Paused', '已暂停'),
 'ui.pause_body': ('Your pile will wait.', '玩偶堆等你回来。'),
 'ui.confirm_title': ('Leave this pile?', '离开这堆玩偶？'),
 'ui.confirm_body': ('This run will be discarded. Your saved standings are safe.', '本次进度将被放弃，已保存的成绩不受影响。'),
 'ui.help_body': ('Solo: Merge matching plushies. Each goal adds 1 minute. Keep the pile below the safety line.',
                  '单人游戏：合成相同玩偶。每达成一个目标，加 1 分钟。让玩偶堆保持在安全线下。'),
 'help.input.keyboard': ('A/D or ←/→ to aim · Space to drop · Esc to pause', 'A/D 或方向键瞄准 · 空格投放 · Esc 暂停'),
 'help.input.pointer': ('Move to aim · Click the cabinet to drop', '移动鼠标瞄准 · 点击柜内投放'),
 'help.input.touch': ('Drag inside the cabinet to aim · Lift your finger to drop', '在柜内拖动瞄准 · 松开手指投放'),
 'help.input.gamepad': ('Left stick / D-pad to aim · A to drop · Start to pause', '左摇杆或方向键瞄准 · A 键投放 · Start 键暂停'),
 'hud.score': ('SCORE  {score}', '得分  {score}'),
 'hud.best': ('BEST  {score}', '最佳  {score}'),
 'hud.drops': ('DROPS  {count}', '已投放  {count}'),
 'hud.time': ('TIME  {time}', '剩余时间  {time}'),
 'hud.goal': ('GOAL  {toy}', '目标  {toy}'),
 'hud.next': ('NEXT  {toy}', '下一个  {toy}'),
 'hud.time_short': ('{time}', '{time}'),
 'hud.goal_count': ('GOAL  {toy} × {count}', '目标  {toy} × {count}'),
 'hud.stage': ('GOAL {index}', '目标 {index}'),
 'hud.ready': ('Ready to drop', '可以投放'),
 'hud.reloading': ('Claw reloading…', '夹爪装填中…'),
 'hud.settling': ('Let the pile settle…', '等待玩偶落稳…'),
 'hud.safety': ('Keep the pile below this line', '请让玩偶保持在安全线下'),
 'hud.points': ('+{points}', '+{points}'),
 'hud.discovery': ('COLLECTION  {count} / 11', '已收集  {count} / 11'),
 'stage.first_hugs': ('First hugs', '初次拥抱'),
 'stage.pocket_workshop': ('Pocket workshop', '口袋工坊'),
 'result.resize': ('The screen was resized.', '屏幕尺寸已改变。'),
 'mp.reason_resize': ('The screen was resized.', '屏幕尺寸已改变。'),
 'result.game_over': ('Game over', '游戏结束'),
 'result.target': ('Target completed', '目标已达成'),
 'result.overflow': ('Pile exceeded the safety line', '玩偶堆超出安全线'),
 'result.timeout': ('Time expired', '时间已用完'),
 'result.drops': ('No drops remaining', '投放次数已用完'),
 'result.summary': ('{score} points · {merges} merges · {seconds}s', '{score} 分 · 合成 {merges} 次 · {seconds} 秒'),
 'result.baseline': ('Standard rules', '标准规则'),
 'result.tuned': ('Practice rules', '练习规则'),
 'result.save_failed': ('This score is visible now but could not be saved.', '当前成绩可见，但暂时无法保存。'),
 'leaderboard.unknown_stage': ('Archived challenge', '历史挑战'),
 'leaderboard.empty': ('Your first finished challenge belongs here.', '完成第一个挑战，留下你的成绩。'),
 'leaderboard.row': ('{rank}. {name}   {score} pts', '{rank}. {name}   {score} 分'),
 'leaderboard.detail': ('{stage} · {outcome} · {seconds}s · {rules}', '{stage} · {outcome} · {seconds} 秒 · {rules}'),
 'leaderboard.victory': ('Cleared', '成功'),
 'leaderboard.defeat': ('Attempt', '尝试'),
 'leaderboard.local_note': ('Saved on this device. No account needed.', '保存在当前设备，无需账号。'),
 'error.stage': ('This challenge could not load. Return to the title and choose another.', '无法载入此挑战，请返回主菜单后重新选择。'),
 'error.assets': ('Some game resources are missing. Restore assets and rebuild the template.', '部分游戏资源缺失，请恢复资源后重新构建模板。'),
 'error.title': ('The cabinet needs a moment.', '游戏柜暂时需要休息。'),
 'error.save': ('Could not save on this device.', '无法在此设备保存。'),
 'error.tweak': ('That value is outside the supported range.', '此数值超出支持范围。'),
 'ui.tweaks': ('Tweak Controls', '调节控制'),
 'ui.tweaks_tooltip': ('Owner preview: adjust this template’s tuning', '创作者预览：调整模板参数'),
 'ui.search': ('Search controls', '搜索调节项'),
 'ui.all_categories': ('All categories', '全部分类'),
 'ui.reset': ('Reset', '重置'),
 'ui.reset_all': ('Reset all', '全部重置'),
 'ui.tweak_intro': ('Owner preview. Gameplay changes mark this run as practice.', '创作者预览。修改玩法参数后，本次成绩将标记为练习。'),
 'ui.tweak_values': ('Active: {active}   Requested: {requested}', '当前生效：{active}   请求数值：{requested}'),
 'ui.tweak_saved': ('Saved locally', '已保存到本地'),
 'ui.tweak_pending': ('Saved · waiting for application boundary', '已保存 · 等待生效时机'),
 'ui.on': ('On', '开'),
 'ui.off': ('Off', '关'),
 'ui.value': ('{value}', '{value}'),
 'apply.LIVE': ('Live', '立即生效'),
 'apply.NEXT_ACTION': ('Next action', '下次操作'),
 'apply.NEXT_SPAWN': ('Next toy', '下次生成玩偶'),
 'apply.NEXT_RUN': ('Next run', '下次挑战'),
 'category.UI': ('UI', '界面'),
 'category.GAMEPLAY': ('Gameplay', '玩法'),
 'category.AUDIO': ('Audio', '声音'),
 'category.PLAYER': ('Player', '玩家'),
 'category.ENEMIES': ('Enemies / pile toys', '敌人／堆内玩偶'),
 'category.ENVIRONMENT': ('Environment', '环境'),
 'unit.number': ('', ''),
 'unit.seconds': ('seconds', '秒'),
 'unit.db': ('dB', '分贝'),
 'unit.speed': ('pixels / second', '像素／秒'),
 'unit.pixels': ('pixels', '像素'),
 'toy.0': ('Mochi Chick', '麻薯小鸡'),
 'toy.1': ('Strawberry Slime', '草莓团子'),
 'toy.2': ('Dumpling Cat', '饺子猫'),
 'toy.3': ('Floppy Bunny', '垂耳兔'),
 'toy.4': ('Pudding Pup', '布丁小狗'),
 'toy.5': ('Pocket Octo', '口袋章鱼'),
 'toy.6': ('Star Pillow', '星星抱枕'),
 'toy.7': ('Cloud Sheep', '云朵绵羊'),
 'toy.8': ('Chonky Axolotl', '胖胖美西螈'),
 'toy.9': ('Moon Moth', '月光飞蛾'),
 'toy.10': ('Dream Dragon', '梦境小龙'),
 'tweak.ui.hud.opacity.label': ('HUD opacity', '界面透明度'),
 'tweak.ui.hud.opacity.description': ('Fade gameplay readouts without changing rules.', '调整游戏界面透明度，不改变规则。'),
 'tweak.ui.text.scale.label': ('Text size', '文字大小'),
 'tweak.ui.text.scale.description': ('Scale readable interface text.', '调整界面文字大小。'),
 'tweak.ui.score.visible.label': ('Show score', '显示得分'),
 'tweak.ui.score.visible.description': ('Show or hide the gameplay score readout.', '显示或隐藏游戏得分。'),
 'tweak.ui.reduced_motion.label': ('Reduced motion', '减少动态效果'),
 'tweak.ui.reduced_motion.description': ('Suppress squish, moving particles and pulses.', '关闭挤压、移动粒子和脉冲效果。'),
 'tweak.gameplay.time_limit.label': ('Starting time', '初始时长'),
 'tweak.gameplay.time_limit.description': ('Starting time for the next run. Each completed goal adds one minute.',
                                           '下次游戏的初始时长。每达成一个目标，增加 1 分钟。'),
 'tweak.gameplay.score.multiplier.label': ('Score multiplier', '得分倍率'),
 'tweak.gameplay.score.multiplier.description': ('Multiply merge and goal rewards on the next run.', '下次挑战的合成与目标奖励倍率。'),
 'tweak.gameplay.settle_seconds.label': ('Final settling grace', '最终落稳等待'),
 'tweak.gameplay.settle_seconds.description': ('Wait after the final drop before evaluating an exhausted pile.', '最后一次投放后等待，再判断次数耗尽。'),
 'tweak.gameplay.overflow_seconds.label': ('Overflow grace', '超线宽限时间'),
 'tweak.gameplay.overflow_seconds.description': ('How long a settled toy may remain above the line.', '落稳玩偶可以停留在安全线上方的时间。'),
 'tweak.audio.master.gain.label': ('Master trim', '总音量微调'),
 'tweak.audio.master.gain.description': ('Additional gain below the player’s master setting.', '在玩家总音量设置基础上额外调整增益。'),
 'tweak.audio.music.gain.label': ('Music trim', '音乐微调'),
 'tweak.audio.music.gain.description': ('Additional gain for the single music track.', '调整唯一音乐曲目的额外增益。'),
 'tweak.audio.sfx.gain.label': ('Game effects trim', '游戏音效微调'),
 'tweak.audio.sfx.gain.description': ('Additional gain for gameplay sounds.', '调整游戏音效的额外增益。'),
 'tweak.audio.ui.gain.label': ('Interface trim', '界面音效微调'),
 'tweak.audio.ui.gain.description': ('Additional gain for menu and control sounds.', '调整菜单和控件音效的额外增益。'),
 'tweak.player.aim.speed.label': ('Claw travel speed', '夹爪移动速度'),
 'tweak.player.aim.speed.description': ('Keyboard and gamepad travel speed on the next movement.', '下次键盘或手柄操作的夹爪移动速度。'),
 'tweak.player.claw.open_seconds.label': ('Claw opening time', '夹爪张开时间'),
 'tweak.player.claw.open_seconds.description': ('Time from release request until the toy falls.', '从请求投放到玩偶落下的时间。'),
 'tweak.player.claw.reload_seconds.label': ('Claw reload time', '夹爪装填时间'),
 'tweak.player.claw.reload_seconds.description': ('Time to prepare the next toy after a release.', '投放后准备下一个玩偶所需时间。'),
 'tweak.player.release.spin.label': ('Release rotation', '投放旋转'),
 'tweak.player.release.spin.description': ('Seeded angular impulse for the next release.', '下次投放的固定种子角冲量范围。'),
 'tweak.enemies.toy.bounce.label': ('Toy bounce', '玩偶弹性'),
 'tweak.enemies.toy.bounce.description': ('Bounciness for newly created pile toys.', '新生成玩偶的弹性。'),
 'tweak.enemies.toy.friction.label': ('Toy friction', '玩偶摩擦力'),
 'tweak.enemies.toy.friction.description': ('Surface friction for newly created toys.', '新生成玩偶的表面摩擦力。'),
 'tweak.enemies.toy.gravity.label': ('Toy gravity', '玩偶重力'),
 'tweak.enemies.toy.gravity.description': ('Gravity multiplier for newly created toys.', '新生成玩偶的重力倍率。'),
 'tweak.enemies.toy.squish.label': ('Visual squish', '视觉挤压'),
 'tweak.enemies.toy.squish.description': ('Visual deformation only; collision outlines stay stable.', '仅改变视觉形变，碰撞轮廓保持稳定。'),
 'tweak.environment.filter.enabled.label': ('Screen filter', '画面滤镜'),
 'tweak.environment.filter.enabled.description': ('Enable the warm full-screen color treatment.', '启用全屏暖色滤镜。'),
 'tweak.environment.filter.intensity.label': ('Filter strength', '滤镜强度'),
 'tweak.environment.filter.intensity.description': ('Intensity of the warm screen tint.', '全屏暖色滤镜的强度。'),
 'tweak.environment.particles.label': ('Merge particles', '合成粒子'),
 'tweak.environment.particles.description': ('Particle emission within the fixed safety limit.', '在固定数量上限内调整粒子效果。'),
 'tweak.environment.ambient.label': ('Ambient motes', '环境微粒'),
 'tweak.environment.ambient.description': ('Enable gently floating cabinet dust.', '启用缓慢飘动的柜内微粒。'),
 'tweak.environment.danger.line.label': ('Safety line height', '安全线高度'),
 'tweak.environment.danger.line.description': ('Logical board height used for overflow in the next run.', '下次挑战判定超线的逻辑高度。'),
 'ui.pause_short': ('Ⅱ', 'Ⅱ'),
 'hud.score_label': ('SCORE', '得分'),
 'hud.score_value': ('{score}', '{score}'),
 'hud.goal_label': ('GOAL', '目标'),
 'hud.next_label': ('NEXT', '下一个'),
 'hud.goal_value': ('{toy} × {count}', '{toy} × {count}'),
 'mobile.rotate_title': ('Turn to portrait', '请竖屏游玩'),
 'mobile.rotate_body': ('Mushies uses portrait mode on mobile. Turn your device upright to continue. Your pile and timer will wait.',
                        'Mushies 在移动设备上使用竖屏模式。请将设备竖直后继续，玩偶堆和计时会暂停等待。'),
 'mobile.enter_portrait': ('Use portrait mode', '进入竖屏模式'),
 'help.bombs': ('Puff Bomb has a 1% chance to appear. Its 5-second fuse starts when released and pauses with the game. It disappears '
                  'with every plushie touching it or within 15 px of its edges at detonation. Toys beyond that range survive; clearing '
                  'gives no points.',
                  '蓬蓬炸弹有 1% 的出现概率，放下后 5 秒爆炸，暂停时倒计时也会暂停。它会清除自己和爆炸时接触到或距离其边缘 15 像素以内的玩偶，不会伤及范围外的玩偶，也不会获得分数。'),
 'toy.bomb': ('Puff Bomb', '蓬蓬炸弹'),
 'settings.title': ('Settings', '设置'),
 'settings.close': ('Close', '关闭'),
 'settings.profile': ('Profile', '个人资料'),
 'settings.audio': ('Audio', '声音'),
 'settings.preferences': ('Preferences', '偏好设置'),
 'settings.autosave': ('Changes save automatically', '更改会自动保存'),
 'settings.save_failed': ('Settings could not be saved.', '设置未能保存。'),
 'mp.return': ('Return', '返回'),
 'leaderboard.practice': ('Practice mode · Scores are not saved.', '练习模式 · 不保存成绩。'),
 'leaderboard.row_detail': ('{seconds}s · {outcome}', '{seconds} 秒 · {outcome}')}
COPY.update({'loader.overlay_loading': ('LOADING...', '加载中…')})
COPY.update({'ui.restart_short': ('Restart', '重新开始')})
COPY.update({
 'help.rules': ('Solo runs start with 3 minutes. Time running out or a pile staying above the safety line ends the run. Goals advance without clearing your pile.', '单人游戏每局开始有 3 分钟。时间到或玩偶堆持续超出安全线时，本局结束。达成目标不会清空玩偶堆。'),
 'help.rescue': ('Once per run, a settled pile near the safety line puts a Puff Bomb next in the queue. Your current plushie stays in the claw; drop it to reach the rescue bomb.', '每局一次，玩偶堆接近安全线时，下一个玩偶会变为蓬蓬炸弹。当前夹爪中的玩偶保持不变，投放后即可使用救援炸弹。')
})
# Round-3 plush arcade UI: timer caption, key prompts and the results best badge.
COPY.update({
 'hud.time_label': ('TIME', '剩余时间'),
 'ui.key_space': ('Space', '空格'),
 'ui.key_esc': ('Esc', 'Esc'),
 'ui.key_enter': ('Enter', '回车'),
 'ui.hint_move': ('Choose', '选择'),
 'ui.hint_confirm': ('Confirm', '确认'),
 'result.new_best': ('New best!', '新纪录！'),
})
for i, locale in enumerate(('en', 'zh_CN')):
    (ROOT / 'localization' / f'{locale}.json').write_text(json.dumps({k: v[i] for k, v in COPY.items()}, ensure_ascii=False, indent=2) + '\n')
print(f'Wrote {len(COPY)} matching bilingual keys.')
