"""Record real asset mappings and dimensions without inventing historical prompts."""
from pathlib import Path
import json,hashlib
from PIL import Image
ROOT=Path(__file__).resolve().parents[1]
new=[('title','assets/template/ui/title.webp','opaque title plate; resize 1280×854'),('pause','assets/template/ui/pause.webp','alpha frame; 640×640 nine-slice'),('foreground','assets/template/foregrounds/cabinet_trim.webp','crop (0,705,1536,1024); 336×70; preserved 84 px end caps'),('cursor','assets/template/ui/cursor.png','green-key cleanup, silhouette crop, 32×32; hotspot (6,2)'),('aim_cursor','assets/template/ui/aim_cursor.png','alpha cleanup, silhouette crop, 32×32; hotspot (16,16)')]
bomb_source=Image.open(ROOT/'assets/template/source/puff_bomb.png')
bounds=bomb_source.getchannel('A').point(lambda value:255 if value>100 else 0).getbbox()
bomb_crop=(max(0,bounds[0]-12),max(0,bounds[1]-12),min(bomb_source.width,bounds[2]+12),min(bomb_source.height,bounds[3]+12))
bomb_runtime=Image.open(ROOT/'assets/template/bombs/puff_bomb.webp')
bomb_points=len(json.loads((ROOT/'assets/template/bombs/manifest.json').read_text())['outline'])
new.append(('puff_bomb','assets/template/bombs/puff_bomb.webp',f'alpha bounding-box crop {bomb_crop} with 12 px padding; {bomb_runtime.width}×{bomb_runtime.height} quality-90 WebP; alpha below 20 removed; {bomb_points}-point alpha silhouette, 0.97 collider inset'))
records=[]
for key,runtime,processing in new:
 source=f'assets/template/source/{key}.png'
 records.append({'id':key,'generator':'GPT Image 2','generation_date':'2026-09-07' if key=='puff_bomb' else '2026-09-06','source':source,'runtime':runtime,'prompt':f'assets/template/source/generation-prompts/{key}.txt','source_dimensions':Image.open(ROOT/source).size,'runtime_dimensions':Image.open(ROOT/runtime).size,'processing':processing,'runtime_sha256':'sha256:'+hashlib.sha256((ROOT/runtime).read_bytes()).hexdigest()})
 if key in ('title','cursor','aim_cursor'):
  records[-1]['prompt_status']='Brand-normalized transcription for Mushies; the generated image is unchanged.'
  records[-1]['original_prompt_git_ref']=f'd106a19f1935808960e2f74af226d9fc73cbc18a:assets/template/source/generation-prompts/{key}.txt'
for row in json.loads((ROOT/'assets/template/plushies/runtime/manifest.json').read_text())['assets']:
 key=row['key'];records.append({'id':key,'generator':'GPT Image 2 (retained original project art)','baseline_commit':'29e715d','baseline_commit_date':'2026-09-04','source':f'assets/template/plushies/source/{key}.png','normalized_source':f'assets/template/source/normalized/{key}.png','runtime':f'assets/template/plushies/runtime/{key}.webp','runtime_dimensions':Image.open(ROOT/f'assets/template/plushies/runtime/{key}.webp').size,'processing':'Original normalized crop and collision outline preserved; color encoded as quality-90 WebP with alpha.','historical_prompt':'Not present in baseline; not reconstructed or claimed as original.'})
records.append({'id':'arcade','generator':'GPT Image 2 (retained original project art)','source':'assets/template/source/arcade.png','runtime':'assets/template/plushies/background/arcade.webp','processing':'Resize opaque original to 1280×800 and quality-86 WebP.'})
records.append({'id':'boot','generator':'Derived from retained GPT Image 2 chick','source':'assets/template/source/normalized/chick.png','runtime':'assets/template/ui/boot.png','processing':'186×192 alpha-preserving PNG required by Godot splash loader.'})
for size in (192,512):
 records.append({'id':f'app-icon-{size}','generator':'Derived from retained GPT Image 2 chick','source':'assets/template/source/normalized/chick.png','runtime':f'assets/template/ui/app-icon-{size}.png','processing':f'Fit chick within 82% of a {size}×{size} cream RGB canvas; PNG for mobile web manifest.'})
(ROOT/'assets/template/source/provenance.json').write_text(json.dumps({'assets':records},indent=2,ensure_ascii=False)+'\n')
lines=['# Generated asset provenance','', 'The September 6 template upgrade adds five original static images through GPT Image 2. The September 7 Mushies update adds Puff Bomb through GPT Image 2. Its latest built-in image_gen edit gives it a dark charcoal-plum body without limbs, dotted body seams or a belly patch; a second background-extraction pass supplies genuine alpha. Both exact edit prompts are retained in `generation-prompts/puff_bomb.txt`. Sources are kept here and runtime derivatives have explicit dimensions and processing. No localized text is baked into the assets.','', '| Asset | Source | Runtime | Processing |','| --- | --- | --- | --- |']
for key,runtime,processing in new:lines.append(f'| {key} | `{key}.png` | `{runtime}` | {processing} |')
lines+=['','The title, cursor and aim-cursor prompt files use the current Mushies name. They are marked as brand-normalized transcriptions; their exact original generation prompts remain at the Git references recorded in `provenance.json`. Those three images have not been regenerated. Concept-board title edits have separate records in `concepts/provenance.json`.','', 'The eleven original plushies and arcade background are retained from the existing authored game. Their baseline records identify GPT Image 2. The original generation prompts were not stored in that baseline; this revision does not fabricate them. Source masters, normalized crops, original outlines and baseline commit provenance are preserved in `provenance.json`.','', 'The boot icon is a resized PNG derivative of the original chick. Custom pointer/aim cursors are green-key/alpha cleaned, cropped and resized; hotspots are documented above. The pause frame uses real alpha outside its intended linen/velvet panel. The foreground preserves the cushion ends while its plain center padding stretches.','', 'Nunito supplies English body text and Noto Sans SC the Simplified Chinese body text; Cherry Bomb One, Fredoka and ZCOOL KuaiLe supply the logo, headings and large numbers. All are SIL Open Font License 1.1 fonts shipped as subset WOFF2, each beside its `<Family>-OFL.txt` license under `assets/template/fonts/`. The web loader keeps its own separately pinned loader subset. Fonts are not represented as generated illustrations.','', 'New images were visually inspected as generated and in native UI captures. Original plushies retain their silhouette geometry; every tier passes collider/visual tests. Diagnostic contact sheets and native landscape/portrait captures are build outputs, not runtime art.']
(ROOT/'assets/template/source/GENERATED_ASSET_PROVENANCE.md').write_text('\n'.join(lines)+'\n')
